CREATE TABLE STUDENT
(
	STUD_LNAME VARCHAR(35) NOT NULL,
	STUD_FNAME VARCHAR(35) NOT NULL,
	STUD_INITIAL CHAR(2) NOT NULL,
	STUD_COLLEGE VARCHAR(10) NOT NULL,
	STUD_YEAR NUMERIC(1) NOT NULL,
	STUD_COURSE VARCHAR(35) NOT NULL,
	STUD_CONTACT NUMERIC(10),
	STUD_NUM VARCHAR(10) NOT NULL UNIQUE,
	IS_CLEARED BOOLEAN,
	PRIMARY KEY (STUD_NUM)
);

CREATE TABLE LOAN
(
	LOAN_TYPE VARCHAR(50) NOT NULL,
	LOAN_YEAR NUMERIC(4) NOT NULL,
	LOAN_SEM VARCHAR(3) NOT NULL,
	STUD_NUM VARCHAR(10) NOT NULL UNIQUE,
	PRIMARY KEY (STUD_NUM),
	FOREIGN KEY (STUD_NUM) REFERENCES STUDENT(STUD_NUM)
);

CREATE TABLE STS
(
	STS_BRACKET VARCHAR(2) NOT NULL,
	STUD_NUM VARCHAR(10) NOT NULL UNIQUE,
	PRIMARY KEY (STUD_NUM),
	FOREIGN KEY (STUD_NUM) REFERENCES STUDENT(STUD_NUM)
);

CREATE TABLE BAL_HIST
(
	OUT_BALANCE NUMERIC(8,2) NOT NULL,
	AMT_PAID NUMERIC(8,2) NOT NULL,
	PRIMARY KEY (STUD_NUM),
	FOREIGN KEY (STUD_NUM) REFERENCES STUDENT(STUD_NUM)
);



